version: '2'
services:
  node:
    image: dkatavic/sails-sqlite3
    ports:
      - 1337:1337
    command: tail -f /dev/null # loop infinitly
    working_dir: /app
    volumes:
      - .:/app
    #env_file: .env